#import required libraries
import requests
import json

print('Welcome to the IMDB movie information generator')
print()
print("Generate your own API key from this link - http://www.omdbapi.com/apikey.aspx?__EVENTTARGET=freeAcct&__EVENTARGUMENT=&__LASTFOCUS=&__VIEWSTATE=%2FwEPDwUKLTIwNDY4MTIzNQ9kFgYCAQ9kFgICBw8WAh4HVmlzaWJsZWhkAgIPFgIfAGhkAgMPFgIfAGhkGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYDBQtwYXRyZW9uQWNjdAUIZnJlZUFjY3QFCGZyZWVBY2N0x0euvR%2FzVv1jLU3mGetH4R3kWtYKWACCaYcfoP1IY8g%3D&__VIEWSTATEGENERATOR=5E550F58&__EVENTVALIDATION=%2FwEdAAU5GG7XylwYou%2BzznFv7FbZmSzhXfnlWWVdWIamVouVTzfZJuQDpLVS6HZFWq5fYpioiDjxFjSdCQfbG0SWduXFd8BcWGH1ot0k0SO7CfuulN6vYN8IikxxqwtGWTciOwQ4e4xie4N992dfbpyqd1D&at=freeAcct&Email='")
print()
# run a loop to continue user requests
while True:
    print('--------------WELCOME-----------------------')
    # enter API key received in your mail
    print('Enter your API key: ')
    api_key = input()
    # edit the url based on format provided by omdbapi.com
    base_url = 'http://www.omdbapi.com/?apikey=' + api_key
    print('Enter the Title of the movie: ')
    title = input("> ")
    # format the final url according to how the website scrapes data
    final_url = base_url + '&t=' + title + '&plot=full'
    # obtain the url details by sending a GET request.
    request = requests.get(final_url)
    # obtain the json format tree element to obtain the different details
    data = request.json()
    print()
    # run a try block to see if you inputted wrong API or any obtained data is incorrect
    try:
        print('Title: ',data['Title'])
        print()
        print('Release Date: ',data['Released'])
        print()
        print('Storyline: ',data['Plot'])
        print()
        print('Runtime: ',data['Runtime'])
        print()
        print('Genre: ',data['Genre'])
        print()
        print('Director: ',data['Director'])
        print()
        print('Actors: ',data['Actors'])
        print()
        print('Awards Won: ',data['Awards'])
        print()
        print('Rating: ')
        # this for loop is to obtain the various rating by different organizations separately
        for i in (data['Ratings'][0]).keys():
            print(data['Ratings'][0][i])
        for i in (data['Ratings'][1]).keys():
            print(data['Ratings'][1][i])
        print()
        print('Website: ',data['Website'])
        print()
        print()
    except:
        print('Enter Valid API key generated by your own and come back..... Thanks')
        break
    # ask if more movie details to see
    print('Want more movie info: (Yes/No)')
    # convert any data to lower case
    option = input().lower()
    if option == 'no' or option[0] == 'n':
        print('Thank you for using ')
        break
    print()
